# Generated by Django 3.0.6 on 2020-05-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200521_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='toppings_left',
            field=models.IntegerField(null=True),
        ),
    ]
